"""initial schema

Revision ID: 014fc6a20b8b
Revises: 
Create Date: 2026-03-23 21:41:56.259134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014fc6a20b8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('emails_received', sa.Integer(), nullable=True),
    sa.Column('emails_sent', sa.Integer(), nullable=True),
    sa.Column('new_leads', sa.Integer(), nullable=True),
    sa.Column('leads_interested', sa.Integer(), nullable=True),
    sa.Column('leads_materials_sent', sa.Integer(), nullable=True),
    sa.Column('leads_handoff', sa.Integer(), nullable=True),
    sa.Column('leads_not_interested', sa.Integer(), nullable=True),
    sa.Column('ab_tests_run', sa.Integer(), nullable=True),
    sa.Column('ab_variant_a_wins', sa.Integer(), nullable=True),
    sa.Column('ab_variant_b_wins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('thread_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('account_email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_index(op.f('ix_leads_thread_id'), 'leads', ['thread_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_account_email'), 'rate_limits', ['account_email'], unique=False)
    op.create_table('ab_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('variant_a', sa.Text(), nullable=True),
    sa.Column('variant_b', sa.Text(), nullable=True),
    sa.Column('sent_variant', sa.String(length=10), nullable=True),
    sa.Column('got_reply', sa.Boolean(), nullable=True),
    sa.Column('reply_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_results_lead_id'), 'ab_test_results', ['lead_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('stage_at_time', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('ab_variant', sa.String(length=10), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachment_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_lead_id'), 'messages', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_lead_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_ab_test_results_lead_id'), table_name='ab_test_results')
    op.drop_table('ab_test_results')
    op.drop_index(op.f('ix_rate_limits_account_email'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_leads_thread_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
