from enum import StrEnum


class Stage(StrEnum):
    NEW_REPLY = "NEW_REPLY"
    INTERESTED = "INTERESTED"
    PORTFOLIO_SENT = "PORTFOLIO_SENT"
    IN_DISCUSSION = "IN_DISCUSSION"
    HANDOFF_TO_MANAGER = "HANDOFF_TO_MANAGER"
    ORDER = "ORDER"
    NOT_INTERESTED = "NOT_INTERESTED"
    ARCHIVED = "ARCHIVED"


class ReplyCategory(StrEnum):
    INTERESTED = "INTERESTED"
    NOT_INTERESTED = "NOT_INTERESTED"
    SPAM = "SPAM"
    OUT_OF_OFFICE = "OUT_OF_OFFICE"
    QUESTION = "QUESTION"
    READY_TO_ORDER = "READY_TO_ORDER"
